### ISSUE TITLE
[BUG] ULS certificate verify failed: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Benaglio666** [akamai/uls#33]
Running uls.py:

./uls.py -i etp -f dns -o raw --loglevel debug --edgerc /root/.edgerc --section default

I receive the below error:

022-10-05 14:38:43,691 ULS D UlsMonitoring monitoring thread started...
2022-10-05 14:38:43,692 ULS D UlsMonitoring sleeping 300 sec...
2022-10-05 14:38:43,692 ULS I UlsOutput Selected Output Type: RAW 
2022-10-05 14:38:43,693 ULS D UlsTransformation - No Transformation loaded
2022-10-05 14:38:43,693 ULS I UlsInputCli - selected product: ETP
2022-10-05 14:38:43,694 ULS D Config file '/root/.edgerc' was found and is readable.
2022-10-05 14:38:43,694 ULS D Section 'default' found.
2022-10-05 14:38:43,694 ULS D Required configuration value 'host' found.
2022-10-05 14:38:43,694 ULS D Required configuration value 'client_token' found.
2022-10-05 14:38:43,694 ULS D Required configuration value 'client_secret' found.
2022-10-05 14:38:43,695 ULS D Required configuration value 'access_token' found.
2022-10-05 14:38:43,695 ULS D Required configuration value 'etp_config_id' found.
2022-10-05 14:38:43,695 ULS I UlsInputCli - selected feed: DNS
2022-10-05 14:38:43,695 ULS I UlsInputCli - CLI Command:  python3 -u /opt/siem/scripts/DNS_akamai/ext/cli-etp/bin/akamai-etp --edgerc /root/.edgerc --section default --user-agent-prefix ULS/1.6.0_ETP-DNS event dns -f
2022-10-05 14:38:43,702 ULS I UlsInputCli - started PID[10440]: python3 -u /opt/siem/scripts/DNS_akamai/ext/cli-etp/bin/akamai-etp --edgerc /root/.edgerc --section default --user-agent-prefix ULS/1.6.0_ETP-DNS event dns -f
2022-10-05 14:38:44,706 ULS E UlsInputCli - CLI process [10440] was found stale - Reason:  "Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1122)

How can I fixe this error?

This is my ULS version (only interested in DNS events):

Akamai Unified Log Streamer Version information
ULS Version		1.6.0

EAA Version		n/a
ETP Version		0.3.9
MFA Version		n/a
GC Version		n/a
LINODE Version		n/a

OS Plattform		Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
OS Version		3.10.0-1160.76.1.el7.x86_64
Python Version		3.9.0
Docker Status		False

**Comment by MikeSchiessl** [comment]
Confirmed proxy issue on the host - has been successfully resolved.

Please let me know if there is anything else that is not working.
