### ISSUE TITLE
[BUG]docker compose up is not working.

### ISSUE THREAD

**Issue by hisashiyamaguchi** [akamai/uls#9]
I'm getting started ULS and trying to `docker compose up` on simple directory, but it's not working. Here comes what I'm trying.

```
$ uname -a
Darwin tyo-mpy1d 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

$ pwd
~/uls/docker-compose/simple

$ git branch
* main

$ docker -v
Docker version 20.10.0, build 7287ab3

$ cat docker-compose.yml
version: "3.0"
services:
  etp-threat:
    image: uls:latest
    restart: always
    env_file: etp-threat.env
    volumes:
      - type: bind
        source: ~/.edgerc
        target: /opt/akamai-uls/.edgerc

$ docker login
Authenticating with existing credentials...
Login Succeeded

$ docker compose -D up
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
WARN[0000] invalid non-bool value for BUILDX_NO_DEFAULT_LOAD:
DEBU[0000] serving grpc connection
[+] Building 1.5s (2/3)
[+] Building 1.6s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 52B                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 2B                                                                                                                                                 0.0s
 => ERROR [internal] load metadata for docker.io/library/uls:latest                                                                                                             1.6s
------
 > [internal] load metadata for docker.io/library/uls:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by bitonio** [comment]
Hi @hisashiyamaguchi 

Thanks for trying ULS!
You may need to update slight the docker-compose file, I spotted a typo we'll fix:

Replace

```
image: uls:latest
```
by
```
image: akamai/uls:latest
```

Also, I think docker compose YAML doesn't perform any shell-type substitution so you may need to replace
```
source: ~/.edgerc
```

by

```
source: /Users/<your-mac-userid>/.edgerc
```

Please give it a shot and let us know!

**Comment by hisashiyamaguchi** [comment]
Thanks for the quick follow-up @bitonio - After applying changes that you gave me, I'm now having another issue. It's not urgent though.

```
$ cat docker-compose.yml
version: "3.0"
services:
  etp-threat:
    image: akamai/uls:latest
    restart: always
    env_file: etp-threat.env
    volumes:
      - type: bind
        source: /Users/hyamaguc/.edgerc
        target: /opt/akamai-uls/.edgerc

$ cat etp-threat.env
# This is a sample ENV file for EAA - Threat logs (via ULS)

# GENERIC Config
ULS_LOGLEVEL=DEBUG

# INPUT CONFIGURATION
    # THE INPUT PRODUCT [EAA | ETP | MFA]
    ULS_INPUT=ETP
    # THE INPUT FEED
    #   EAA: [ ADMIN | ACCESS]
    #   ETP: [ THREAT | AUP ]
    #   MFA: [ POLICY | AUTH ]
    ULS_FEED=THREAT
    # INPUT FORRMAT
    ULS_FORMAT=JSON
    # LOCATION OF THE AKAMAI .EDGERC FILE
    ULS_EDGERC='/opt/akamai-uls/.edgerc'
    # RELEVANT SECTION WITHIN THE EDGERC FILE
    ULS_SECTION=assets

# OUTPUT CONFIGURATION
    # OUTPUT PATH [ TCP / UDP / HTTP ]
    ULS_OUTPUT=TCP
    # OUTPUT TARGET HOST
    ULS_OUTPUT_HOST=192.168.86.34
    # OUTPUT TARGET PORT
    ULS_OUTPUT_PORT=9091

$ docker login
Authenticating with existing credentials...
Login Succeeded

$ docker compose -D up
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
[+] Running 1/1
 ⠿ simple_etp-threat_1  Restarted                                                                                                                                               0.3s
Attaching to simple_etp-threat_1
etp-threat    | 2021-07-26 22:51:53,195 ULS D Logging initialized
etp-threat    | 2021-07-26 22:51:53,195 ULS D UlsMonitoring monitoring thread started...
etp-threat    | 2021-07-26 22:51:53,195 ULS D UlsMonitoring sleeping 300 sec...
etp-threat    | 2021-07-26 22:51:53,195 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:51:53,195 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:51:53,195 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:51:53,197 ULS D UlsInputCli - started PID[9]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:51:55,202 ULS E UlsInputCli - process [9] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:51:55,202 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:51:55,202 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:51:55,202 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:51:55,204 ULS D UlsInputCli - started PID[10]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:51:57,211 ULS E UlsInputCli - process [10] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:51:57,211 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:51:57,211 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:51:57,211 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:51:57,214 ULS D UlsInputCli - started PID[11]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:51:59,225 ULS E UlsInputCli - process [11] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:51:59,226 ULS C Not able to start the CLI for ETP. See above errors. Giving up after 3 retries.
etp-threat    | 2021-07-26 22:53:08,013 ULS D Logging initialized
etp-threat    | 2021-07-26 22:53:08,013 ULS D UlsMonitoring monitoring thread started...
etp-threat    | 2021-07-26 22:53:08,014 ULS D UlsMonitoring sleeping 300 sec...
etp-threat    | 2021-07-26 22:53:08,014 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:53:08,014 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:53:08,014 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:53:08,016 ULS D UlsInputCli - started PID[9]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:53:10,027 ULS E UlsInputCli - process [9] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:53:10,027 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:53:10,027 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:53:10,028 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:53:10,030 ULS D UlsInputCli - started PID[10]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:53:12,041 ULS E UlsInputCli - process [10] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:53:12,041 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:53:12,041 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:53:12,041 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:53:12,045 ULS D UlsInputCli - started PID[11]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:53:14,056 ULS E UlsInputCli - process [11] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:53:14,056 ULS C Not able to start the CLI for ETP. See above errors. Giving up after 3 retries.
etp-threat    | 2021-07-26 22:58:32,916 ULS D Logging initialized
etp-threat    | 2021-07-26 22:58:32,916 ULS D UlsMonitoring monitoring thread started...
etp-threat    | 2021-07-26 22:58:32,916 ULS D UlsMonitoring sleeping 300 sec...
etp-threat    | 2021-07-26 22:58:32,916 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:58:32,916 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:58:32,917 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:58:32,918 ULS D UlsInputCli - started PID[8]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:58:34,928 ULS E UlsInputCli - process [8] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:58:34,929 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:58:34,929 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:58:34,929 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:58:34,932 ULS D UlsInputCli - started PID[9]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:58:36,938 ULS E UlsInputCli - process [9] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:58:36,938 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 22:58:36,938 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 22:58:36,938 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:58:36,942 ULS D UlsInputCli - started PID[10]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 22:58:38,948 ULS E UlsInputCli - process [10] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 22:58:38,948 ULS C Not able to start the CLI for ETP. See above errors. Giving up after 3 retries.
etp-threat    | 2021-07-26 23:03:13,548 ULS D Logging initialized
etp-threat    | 2021-07-26 23:03:13,549 ULS D UlsMonitoring monitoring thread started...
etp-threat    | 2021-07-26 23:03:13,549 ULS D UlsMonitoring sleeping 300 sec...
etp-threat    | 2021-07-26 23:03:13,549 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 23:03:13,549 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 23:03:13,549 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 23:03:13,550 ULS D UlsInputCli - started PID[9]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 23:03:15,559 ULS E UlsInputCli - process [9] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 23:03:15,560 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 23:03:15,560 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 23:03:15,560 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 23:03:15,564 ULS D UlsInputCli - started PID[10]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 23:03:17,576 ULS E UlsInputCli - process [10] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 23:03:17,576 ULS D UlsInputCli - selected product: ETP
etp-threat    | 2021-07-26 23:03:17,576 ULS D UlsInputCli - selected feed: THREAT
etp-threat    | 2021-07-26 23:03:17,576 ULS D UlsInputCli - CLI Command:  ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 23:03:17,578 ULS D UlsInputCli - started PID[11]: ['python3', 'ext/cli-etp/bin/akamai-etp', '--edgerc', "'/opt/akamai-uls/.edgerc'", '--section', 'assets', '--user-agent-prefix', 'ULS/0.9.0_ETP-THREAT', 'event', 'threat', '-f']
etp-threat    | 2021-07-26 23:03:19,582 ULS E UlsInputCli - process [11] exited RC=1, REASON: Traceback (most recent call last):
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 443, in <module>
etp-threat    |     main()
etp-threat    |   File "/opt/akamai-uls/uls/ext/cli-etp/bin/akamai-etp", line 382, in main
etp-threat    |     client_token=config.client_token,
etp-threat    | AttributeError: 'EdgeGridConfig' object has no attribute 'client_token'
etp-threat    |  -
etp-threat    | 2021-07-26 23:03:19,583 ULS C Not able to start the CLI for ETP. See above errors. Giving up after 3 retries.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2759661]

goroutine 113 [running]:
github.com/docker/compose-cli/local.(*composeService).attachContainerStreams.func1(0x34c7c00, 0xc00055a100, 0x34aac80, 0xc00003a1c0, 0x0, 0x0)
	github.com/docker/compose-cli/local/compose.go:412 +0x61
created by github.com/docker/compose-cli/local.(*composeService).attachContainerStreams
	github.com/docker/compose-cli/local/compose.go:409 +0x12c
```

**Comment by bitonio** [comment]
Hi @hisashiyamaguchi 

It looks like your `.edgerc` file is missing the `client_token` variable in the `[default]` section.
We know these can be hard to get started, we have added a special documentation about how to configure credentials.
Please check it out:
https://github.com/akamai/uls/blob/main/docs/AKAMAI_API_CREDENTIALS.md#etp-open-api-reporting

**Comment by MikeSchiessl** [comment]
Hi @hisashiyamaguchi,

can you please change your docker-compose.yml to use the akamai/uls:development image instead of the latest image?
I've just added a .edgerc verification logic in order to give a more detailed output on missing variables within the config file.
Please provide any feedback on this topic.

**Comment by MikeSchiessl** [comment]
Hi @hisashiyamaguchi ,

have you been able to re-test the issue with the mentioned "development" branch?
